version: '3'
services:
  keycloak:
    image: jboss/keycloak
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER='hans'
      - KEYCLOAK_PASSWORD='wurst'
  smtp:
    image: mailhog/mailhog
    ports:
      - "8025:8025"